Style/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/GuardClause:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundBlockParameters:
  Enabled: false

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/ParameterLists:
  Max: 13
